dist: trusty
group: travis_latest

language: ruby

install: skip

script:
  - ruby calculator_test.rb

deploy:
  - provider: pages # check the site at https://iriberri.github.io/ruby-test-example/
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
